name: Aggregate Fantasy Standings

on:
  # Manuell starten können
  workflow_dispatch: {}
  # Oder automatisch, wenn neue Saison-TSVs eingecheckt werden
  push:
    paths:
      - "output/3082897-history-standings/*.tsv"

permissions:
  contents: write   # nötig, damit wir committen & pushen dürfen

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # sauberer Commit/Push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # falls du requirements.txt hast:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # pandas o.ä. nur wenn dein Aggregationsscript es wirklich braucht
          # pip install pandas

      - name: Run aggregation script
        # 👉 Falls dein Script anders heißt/liegt, HIER anpassen:
        run: |
          set -e
          python aggregate_managers_all_time.py
          # Wenn dein Skript stattdessen unter scripts/ liegt:
          # python scripts/aggregate_standings.py

      - name: Commit results (if changed)
        run: |
          set -e
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 👉 Pfad des Outputs anpassen, falls dein Script woanders hinschreibt
          # Für aggregate_managers_all_time.py:
          OUT="output/all_time/aggregated_standings.tsv"
          # Für dein altes scripts/aggregate_standings.py ggf.:
          # OUT="output/3082897-history-standings/aggregated_standings.tsv"

          if [ -f "$OUT" ]; then
            git add "$OUT"
          else
            echo "Output file not found: $OUT"
            exit 1
          fi

          # Nur committen, wenn es Änderungen gibt
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update aggregated standings"
          git push
