name: etl
on:
  schedule:
    - cron: "0 5 * * 2"     # Di 05:00 UTC (06:00 Berlin Winter)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run ETL
        run: |
          python3 etl/parse_weeks.py
          python3 etl/build_json.py
      - name: Commit processed data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/processed public/data/processed || true
          git commit -m "auto: update processed JSONs" || echo "nothing to commit"
          git push
