name: FF Scraping

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Welches Script soll laufen?"
        type: choice
        required: true
        default: scrapeStandings
        options:
          - scrapeStandings
          - aggregateStandings
          - scrapeGamecenter
          - analyzeGamecenter
  schedule:
    - cron: "0 7 * * 1"  # montags 07:00 UTC (~09:00 Berlin)

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Falls du ENV in constants.py nutzt, sonst ignoriert:
      LEAGUE_ID: ${{ vars.LEAGUE_ID }}
      LEAGUE_START_YEAR: ${{ vars.LEAGUE_START_YEAR }}
      LEAGUE_END_YEAR: ${{ vars.LEAGUE_END_YEAR }}
      COOKIE_STRING: ${{ secrets.COOKIE_STRING }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run selected script
        run: |
          case "${{ github.event.inputs.script }}" in
            "scrapeStandings")  python scrapeStandings.py ;;
            "aggregateStandings") python aggregateStandings.py ;;
            "scrapeGamecenter") python scrapeGamecenter.py ;;
            "analyzeGamecenter") python analyzeGamecenter.py ;;
          esac

      - name: Upload CSV artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-csv
          path: |
            output/**/*.csv
            output/*.csv

      - name: Commit & push output (optional)
        run: |
          if ls output 1>/dev/null 2>&1; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add output || true
            if ! git diff --cached --quiet; then
              git commit -m "chore: update output CSVs [skip ci]"
              git push
            else
              echo "No changes to commit."
            fi
          fi
