# .github/workflows/sleeper-draft.yml
name: Sleeper Draft Export
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run draft scraper
        env:
          SLEEPER_LEAGUE_ID: ${{ secrets.SLEEPER_LEAGUE_ID }}
          SEASON: "2022"   # oder leer lassen -> Script liest league.season
        run: python scrapeSleeperDraft.py
      - name: Commit & push
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Export draft.tsv" || echo "No changes"
          git push
